name: portfolio
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.5
  google_fonts: ^3.0.1
  flutter:
    sdk: flutter
  unicons: ^2.1.0
  flutter_svg: ^1.1.6
  animated_text_kit: ^4.2.2
  url_launcher: ^6.1.6
  flutter_dotenv: ^5.0.2
  emailjs: ^1.0.0
  either_dart: ^0.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/project/
    - assets/images/banner/
    - assets/images/certificated/
    - assets/logo/

